export const DEFAULT_QUESTIONS: string[] = [
  "Who is the coolest person in the group?",
  "Who does the worst karaoke?",
  "Who's the best DJ?",
  "Who is the best behaved?",
  "Who has the worst-smelling farts?",
  "Who is the nosiest person?",
  "Who is the best cook?",
  "Who would accidentally become famous?",
  "Who would survive the zombie apocalypse?",
  "Who is most likely to get a DUI?",
  "Who is most likely to marry someone they met 48 hours ago?",
  "Who would be most likely to disappear for a year and come back with a completely different life?",
  "Who cares the least about anything?",
  "Who would be the best sugar baby?",
  "Who would be the best sugar daddy?",
  "Who would be the first person abducted by aliens?",
  "Who would aliens return immediately after abducting them?",
  "Who would be the hardest person to explain to an alien?",
  "Who would be the most dangerous person if they suddenly became a billionaire?",
  "Who would become the weirdest old person?",
  "Who would be the first person to die in a horror movie?",
  "Who sends the most messages and contributes the least information?",
  "Who sees the message immediately but waits 3 hours to reply on purpose?",
  "Who would secretly have a second group chat without one person in this group?",
  "Who screenshots messages and sends them to someone outside the group?",
  "Who says “I’m never drinking again” every single weekend?",
  "Who would have absolutely no memory of how they got home?",
  "Who would wake up with the most unexplained photos in their camera roll?",
  "Who would say “I’m only having one drink” and be the last person awake?",
  "Who would get drunk the fastest and still insist they’re completely sober?",
  "Who would become everyone’s best friend after two drinks?",
  "Who would order the weirdest drink just because it looks cool?",
  "Who could find a man’s entire family tree from one Instagram photo?",
  "Who would notice first that someone unfollowed someone?",
  "Who would say “don’t tell anyone” to five different people?",
];
